const BaseCmd = require("../cmd-types/basecmd.js");
const { MessageAttachment } = require("discord.js");

class AICatPicCmd extends BaseCmd
{
	constructor(baseArgs)
	{
		super(...baseArgs);
		this.url     = `https://${this.domain = "thiscatdoesnotexist"}.com`;
		this.attname = `${this.domain}.jpeg`;
	}

	// 0 on success
	/*Number*/ call(/*Discord.Message*/ msg, /*Array<String>*/ args)
	{
		if (super.call(msg, args)) return 1;
		msg.channel.send(
			`Cat generated by <${this.url}>`,
			new MessageAttachment(this.url, this.attname)
		);
		return 0;
	}
}

module.exports = AICatPicCmd;
